
services:
  deephole_stock_db_init:
    image: deephole-stock-data:6.0
    container_name: deephole_stock_db_init
    build:
      context: ..
      dockerfile: docker/Dockerfile
    command: python /app/sql/init_db.py
    volumes:
      - ${DATA_VOLUME}:/data
      - ${LOG_VOLUME}:/logs
    restart: "no"
    environment:
      - PYTHONPATH=/app 
      - ENABLE_CRON=false

  deephole_stock_api_service:
    image: deephole-stock-data:6.0
    container_name: deephole_stock_api_service
    depends_on:
      - deephole_stock_db_init
    volumes:
      - ${DATA_VOLUME}:/data
      - ${LOG_VOLUME}:/logs
      - /var/run/docker.sock:/var/run/docker.sock
    privileged: true
    environment:
      - PYTHONPATH=/app 
      - TZ=${TIME_ZONE}
      - API_SERVICE_NAME=deephole_stock_api_service
      - API_PORT=${API_PORT}
      - ENABLE_CRON=false
      - IFIND_REFRESH_TOKEN=${IFIND_REFRESH_TOKEN}
      - NUMBA_NUM_THREADS=auto
      - OMP_NUM_THREADS=auto
      - MKL_NUM_THREADS=auto
    ports:
      - "${API_PORT}:${API_PORT}"
    command: uvicorn api:app --host 0.0.0.0 --port ${API_PORT}
    restart: unless-stopped
    

  deephole_stock_cron_fetcher:
    image: deephole-stock-data:6.0
    container_name: deephole_stock_cron_fetcher
    depends_on:
      - deephole_stock_db_init
    volumes:
      - ${DATA_VOLUME}:/data
      - ${LOG_VOLUME}:/logs
      - /var/run/docker.sock:/var/run/docker.sock
    privileged: true
    environment:
      - PYTHONPATH=/app 
      - TZ=${TIME_ZONE}
      - API_SERVICE_NAME=deephole_stock_api_service
      - API_PORT=${API_PORT}
      - DASHBOARD_SERVICE_NAME=deephole_stock_dashboard
      - DASHBOARD_PORT=${DASHBOARD_PORT}
      - STOCK_FETCHER_SERVICE_NAME=deephole_stock_cron_fetcher
      - ENABLE_CRON=true
      - CRON_SCHEDULE_CN=${CRON_SCHEDULE_CN}
      - CRON_SCHEDULE_HK=${CRON_SCHEDULE_HK}
      - CRON_SCHEDULE_US=${CRON_SCHEDULE_US}
    restart: unless-stopped

  # deephole_stock_dashboard:
  #   image: deephole-stock-data:6.0
  #   container_name: deephole_stock_dashboard
  #   depends_on:
  #     - deephole_stock_db_init
  #     - deephole_stock_api_service
  #   volumes:
  #     - ${DATA_VOLUME}:/data
  #     - ${LOG_VOLUME}:/logs
  #   environment:
  #     - TZ=${TIME_ZONE}
  #     - API_SERVICE_NAME=deephole_stock_api_service
  #     - API_PORT=${API_PORT}
  #     - DASHBOARD_PORT=${DASHBOARD_PORT}
  #     - ENABLE_CRON=false
  #   ports:
  #     - "${DASHBOARD_PORT}:${DASHBOARD_PORT}"   # 👈 从 .env 读取端口
  #   command: streamlit run dashboard.py --server.port ${DASHBOARD_PORT} --server.address 0.0.0.0
  #   restart: unless-stopped

  deephole_stock_dashboard:
    image: deephole-stock-data:6.0
    container_name: deephole_stock_dashboard

    depends_on:
      - deephole_stock_db_init
      - deephole_stock_api_service

    volumes:
      - ${DATA_VOLUME}:/data
      - ${LOG_VOLUME}:/logs
      - /var/run/docker.sock:/var/run/docker.sock
    privileged: true
    environment:
      - TZ=${TIME_ZONE}
      - API_SERVICE_NAME=deephole_stock_api_service
      - API_PORT=${API_PORT}
      - DASHBOARD_PORT=${DASHBOARD_PORT}
      - ENABLE_CRON=false
    ports:
      - "${DASHBOARD_PORT}:3000"

    command: nginx -g "daemon off;"
    restart: unless-stopped

volumes:
  duckdb_data:
  duckdb_logs: